name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv
        pip install django-cryptography
        pip install requests
        pip install -r requirements.txt
    - name: Deploy server
      run: |
        pip install Django
        apt install sqlite3
        python manage.py makemigrations LegacySite
        python manage.py makemigrations
        python manage.py migrate
        sh import_dbs.sh
        python manage.py runserver
    - name: Run Tests
      run: |
        python manage.py test

